mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('voteapp/')),
    url(r'^voteapp/', include('voteapp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

voteapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

app_name = 'voteapp'

urlpatterns = [
    # ex: /voteapp/
    url(r'^$', views.home, name='index'),

    # ex: /voteapp/elections
    url(r'^elections/$', views.eligible_elections, name='elections'),

    # ex: /voteapp/election5/
    url(r'^election(?P<election_id>[0-9]+)/$', views.election_detail, name='election_detail'),

    # ex: /voteapp/election5/ballot1
    url(r'^election(?P<election_id>[0-9]+)/ballot(?P<ballot_id>[0-9]+)/$', views.election_detail, name='election_detail_ballot'),

     # ex: /voteapp/results
    url(r'^results/$', views.election_summary, name='election_summary'),

    # ex: /voteapp/view_logs
    # ex: /voteapp/results
    url(r'^view_logs/$', views.view_logs, name='view_logs'),

    # ex: /voteapp/register
    url(r'^register/$', CreateView.as_view(template_name='voteapp/register.html', form_class=UserCreationForm, success_url='/'), name='register'),

    url(r'^login/$', auth_views.login, {'template_name': 'voteapp/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'voteapp/logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
]

voteapp/forms.py
from django import forms

from django.utils.translation import ugettext as _





class WriteInForm(forms.Form):
    write_in_form = forms.CharField(widget=forms.TextInput, required=False, max_length=200,label="Add a write in option")


class MultiVoteForm(forms.Form):

    def __init__(self, *args, **kwargs):

        dynamic_form = kwargs.pop('extra')
        self.form_type = dynamic_form['type']
        self.max_choices = dynamic_form['max_choices']
        super(MultiVoteForm, self).__init__(*args, **kwargs)


        if self.form_type == 'ranked':
            choices = []
            for i in range(1,len(dynamic_form['option_list'])+1):
                choices.append((i,i))
            choices.append(('',''))
            for option in dynamic_form['option_list']:
                print(option)
                self.fields['choice_{}-{}'.format(option['type'], option['obj'].id)] = forms.ChoiceField(label=option['obj'].option_text, choices=choices, required=False)

        if self.form_type == 'checkbox':
            for option in dynamic_form['option_list']:
                print(option)
                self.fields['choice_{}-{}'.format(option['type'], option['obj'].id)] = forms.BooleanField(label=option['obj'].option_text, required=False)

        if self.form_type == 'radio':
            choices = []
            for option in dynamic_form['option_list']:
                #options types are 'normal' or 'write_in'
                choices.append(('{}-{}'.format(option['type'], option['obj'].id),option['obj'].option_text,))

            self.fields['choice'] = forms.ChoiceField( widget=forms.RadioSelect(), choices=choices, required=False)


    def dynamic_answers(self):
        for name, value in self.cleaned_data.items():
            if name.startswith('choice_'):
                yield (self.fields[name].label, value)

    def clean(self):
        cleaned_data = super(MultiVoteForm, self).clean()
        if self.form_type == "ranked":
            #make sure no duplicate ranks exist
            no_dups = {}

            for key, value in cleaned_data.items():
                if value:
                    if value not in no_dups:
                        no_dups[value] = [key]
                    else:
                        #duplicate value, raise error
                        no_dups[value].append(key)

            for value,key in no_dups.items():
                if len(key) > 1:
                    for k in key:
                        self.add_error(k,"Two options cannot have the same rank.")

        if  self.form_type == "checkbox":
            #make sure no more than max choices
            print("hiiiiiii")
            print(self.max_choices)

            count_selected = 0
            for item, value in cleaned_data.items():
                if value:
                    count_selected += 1
            print(count_selected)
            if self.max_choices:
                if count_selected > self.max_choices:
                    print("raising error")
                    raise forms.ValidationError(_("The maximum number of choices is {}.".format(self.max_choices)), code="MORE_THAN")

voteapp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import Http404
from django.db.models import Max

from .models import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from voteapp.forms import MultiVoteForm, WriteInForm
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views

from django.utils import timezone
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
import pdb
from django.contrib.auth.signals import user_logged_in, user_logged_out

def home(request):

    """
    Gets the template for the homepage and displays it

    :param request: HTTP object containing django state
    :return: HTTP filled template
    """
    log(request.user, "Load Home Page")
    return render(request, 'voteapp/index.html', {})




def is_eligible(request, election_id):
    """
        Checks that the current user is registered for election with id passed in.
        If eligible returns true,  otherwise return 404 indicating, not registered

    :param request: : HTTP object containing django state
    :param election_id: ID of election model object to test users eligigibility
    :return: True if eligible or an HTTP error

    """

    if request.user.election_set.filter(id=election_id): #make sure user is elegible to vote
        return True
    else:
        raise Http404("You are not registered for this election.")


@login_required(login_url='/voteapp/login/')# redirects to login page if not logged in
def eligible_elections(request):
    """
        Creates a list of the elections that the logged in user is registered for.

    :param request: HTTP object containing django state and current user
    :return: HTTP filled template showing eligible elections
    """

    template_name = 'voteapp/elections.html'
    context_object_name = 'election_list' #variable to accesse in template
    current_user = request.user
    elections = current_user.election_set.all()
    return render(request, template_name, {context_object_name: elections})



def get_ballot_options(request, ballot):
    """
        This function returns a dictionary used for creating dynamic forms, it contains:


    :param request: HTTP object containing django state and current user
    :param ballot: ballot object (from models), it is connected to one election and has one ballot question
    :return: dictionary used to create dynamic forms:
        {'type': 'ranked' or 'checkbox' or 'radio',
        'allow_custom': True or False,
        'max_choices': int,
        'option_list':
                [{'type':'normal' or 'write_in',
                  'obj': option_obj or write_in_option_obj (from model)}, ...]
    """

    dynamic_form = {'type': ballot.type, 'allow_custom':ballot.allow_custom, 'max_choices':ballot.max_num}
    dynamic_form['option_list'] = []
    for opt in ballot.option_set.all():

        dynamic_form['option_list'].append({'type':'normal', 'obj':opt})
    if ballot.allow_custom:
        dynamic_form['allow_custom'] = True
        for write_in in request.user.writeinoption_set.filter(ballot_item=ballot.id):

            dynamic_form['option_list'].append({'type':'write_in', 'obj':write_in})

    return dynamic_form



@login_required(login_url='/voteapp/login/')
def add_write_in(request, election_id, ballot_id, write_in):
    """
        Creates a write in option if it doesn't already exist and saves it to the db.

    :param request: HTTP object containing django state and current user to link to write in object
    :param election_id: id of current election model
    :param ballot_id: id of current ballot model
    :param write_in: text of write in option to be added
    :return: None (new write in obejct is written to db)

    """
    if is_eligible(request, election_id): #authenticate user or return error

        max_display_order = WriteInOption.objects.all().aggregate(Max('display_order'))['display_order__max']
        wio = WriteInOption.objects.filter(option_text=write_in).first()
        if not wio:
            wio = WriteInOption()
            wio.ballot_item = Ballot.objects.get(id=ballot_id)
            wio.option_text = write_in
            wio.display_order =  max_display_order + 10
            wio.save()
        wio.voters.add(request.user)
        log(request.user, "Added Write in option: {}".format(str(wio)))


def save_vote(user, ballot_id, clean_data):
    """
        Deletes any previous votes on this ballot(voting item) and then addes vote to DB

    :param user: model of Current user needed to link to vote
    :param ballot_id: id of current ballot model
    :param clean_data: dictionary of dynamic data based on type of form filled out:
                    if ballot type is ranked:
                        key: choice_normal-<id> or write_in-<id> ie: write_in-1
                        value: Rank Chosen (int) 1 through number of options
                    if ballot type is radio:
                        key: 'choice'
                        value: "normal-<id>" or "write_in-<id>" ie: normal-1
                    if ballot type is checkbox:
                        key: choice_normal-<id> or write_in-<id> ie: write_in-1
                        value: True
    :return: None -
        The new vote object created will be added to the db, if it is a write in the option will be set to null,
        if it is a normal option then the custom_option will be set to null
    """

    #if voter has already voted update vote

    #remove any previous votes from this voter
    Votes.objects.filter(ballot=ballot_id).filter(voter=user.id).delete()
    ballot = Ballot.objects.get(id=ballot_id)

    if ballot.type == "ranked":
        for option, value in clean_data.items():
            if value:
                #add vote for each ranked item
                vote = Votes()
                vote.voter = user
                vote.time_stamp = timezone.now()
                vote.value = value
                vote.ballot = ballot
                if "choice_normal" in option:
                    id = option.split("-")[1]
                    vote.custom_option = None
                    vote.option = Option.objects.get(id=id)
                else:
                    id = option.split("-")[1]
                    vote.option = None
                    vote.custom_option = WriteInOption.objects.get(id=id)
                vote.save()
                log(user, "Entered Vote: {}".format(str(vote)))
    elif ballot.type == 'radio':
        for option, value in clean_data.items():
            if value:
                opt_type, id = value.split("-")
                #value is the id of the option selected

                vote = Votes()
                vote.voter = user
                vote.time_stamp = timezone.now()
                vote.value = None
                vote.ballot = ballot
                if opt_type == "normal":
                    vote.custom_option = None
                    vote.option = Option.objects.get(id=id)
                elif opt_type == "write_in":
                    vote.option = None
                    vote.custom_option = WriteInOption.objects.get(id=id)
                vote.save()
                log(user, "Entered Vote: {}".format(str(vote)))
    elif ballot.type == 'checkbox':
        for option, value in clean_data.items():
            print("Option: {}, Value: {}".format(option, value))
            if value:
                opt_type, id = option.split("-")
                #value is the id of the option selected

                vote = Votes()
                vote.voter = user
                vote.time_stamp = timezone.now()
                vote.value = value
                vote.ballot = ballot
                if opt_type == "choice_normal":
                    vote.custom_option = None
                    vote.option = Option.objects.get(id=id)
                elif opt_type == "choice_write_in":
                    vote.option = None
                    vote.custom_option = WriteInOption.objects.get(id=id)
                vote.save()
                log(user, "Entered Vote: {}".format(str(vote)))
def get_next_ballot(election, ballot_id):
    """
        Gets the ballot with the next largest display  order if there is one or returns None

    :param election: election object from models containing current election
    :param ballot_id: id of ballot from models containing current ballot
    :return: next_ballot: the next largest display_order ballot in this election, or None
    """

    ballots = election.ballot_set.all().order_by('display_order')
    get_next = False
    next_ballot = None

    for ballot in ballots:
        if get_next:
            next_ballot = ballot
            break
        if str(ballot.id) == str(ballot_id):
            get_next = True
            print("Setting get_next to true")


    return next_ballot


@login_required(login_url='/voteapp/login/')
def election_detail(request, election_id, ballot_id=None):
    """
    The main control of app is in this function. It gets the election and ballot objects from db based on the
    url (election1/ballot3/) the number following it is the id param passed in (this is done in urls.py).  If ballot_id
    is None it shows a list of the ballots in the election and a start button.

    If a write in option was added it adds it to the database and then reloads this function to display with new option.

    All the relevant normal options and write in options are retreived and then passed into the MultiVoteForm to create dynamic
    forms based on the type of ballot it is.  When the form is submitted this same function is called and loaded with the

voteapp/templates/voteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VoteApp</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'voteapp/bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'voteapp/style.css' %}" />
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <ul class="navbar-static-top navbar-nav nav">
            <li><a href="/voteapp/">Home</a></li>

            <li><a href="/voteapp/results">Results</a></li>
            {% if user.is_staff %}
                <li><a href="/voteapp/view_logs">View Logs</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a href="/voteapp/logout">Logout {{ user.first_name }}</a></li>
            {% else %}
                <li><a href="/voteapp/login">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

voteapp/templates/voteapp/detail.html
{% extends 'voteapp/base.html' %}
{% block content %}
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'voteapp:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>
{% endblock %}

voteapp/templates/voteapp/election_detail.html
{% extends 'voteapp/base.html' %}
{% block content %}
<div class="container">
    <h1 class="well well-lg text-center">{{ election.name }}</h1>

    {% if error_message %}<p><div class="alert alert-danger">{{ error_message }}</div></p>{% endif %}

    {% if ballot %}
        <form action="." method="post">
        {% csrf_token %}
        <h2>{{ballot.ballot_title}}</h2>
        {% if ballot.how_to_vote %}<h3>{{ballot.how_to_vote | linebreaksbr}}</h3>{% endif %}
        {% if ballot.ballot_question %}<h4><strong>{{ballot.ballot_question| linebreaksbr}}</strong></h4>{% endif %}
        {% if ballot.ballot_details %}<p><em>{{ballot.ballot_details| linebreaksbr}}</em></p>{% endif %}

        {% if ballot.get_options %}
            {{ form.non_field_errors }}
            {% if ballot.type == 'ranked' %}
                <div class="row top-buffer  container">

                    <div class="form-group ">



                        {% for field in form %}
                        <div class="row well well-sm">

                            {{ field.errors }}

                            <div class="col-sm-2 text-center">
                            {{ field }}
                            </div>
                            <div class="col-sm-8">
                                {{ field.label_tag |linebreaksbr }}
                            </div>



                        </div>

                        {% endfor %}



                    </div>
                </div>

            {% elif ballot.type == 'radio' %}


                <div >
                        {% for field in form %}
                        <div class="row well well-sm">

                            {{ field.errors }}

                            <div class="radio">
                            {{ field }}
                            </div>

                        </div>
                        {% endfor %}
                </div>
            {% elif ballot.type == 'checkbox' %}


                <div >
                        {% for field in form %}
                        <div class="row well well-sm">

                            {{ field.errors }}

                            <div class="checkbox">
                            {{ field }}{{ field.label_tag |linebreaksbr }}
                            </div>

                        </div>
                        {% endfor %}
                </div>
            {% endif %}


        {% endif %}
        {% if write_in_form %}
            {{ write_in_form.non_field_errors }}

            {% for field in write_in_form %}
            <div class="row well well-sm">
                <div class="col-sm-5">
                    {{ field.label_tag |linebreaksbr }}
                </div>
                <div class="col-sm-5 text-center">
                {{ field }}
                </div>

                <button name="Add" type="submit" value="Add"  class="col-sm-2 text-center">
                ADD
                </button>

            </div>
            {% endfor %}
        {% endif %}
            <div class="text-center top-buffer">
                <a href="{% url 'voteapp:election_detail' election.id %}"><button name="Save" type="submit" value="Save" class="btn-lg">SAVE</button></a>

            </div>

        </form>

    {% else %}
        <p>There are {{ election.ballot_set.count }} items on this ballot, click start to begin or select an item below to go directly to that ballot item.</p>
        <div class="text-center top-buffer">
            <a href="{% url 'voteapp:election_detail_ballot' election.id election.get_ballots.first.id %}"><button class="btn-lg">START</button></a>
        </div>
    {% endif %}

    <div class="footer well well-md">
        <p>Jump to a specific ballot item:</p>
        <ul class="nav nav-pills nav-stacked text-center">

        {% for each_ballot in election.ballot_set.all %}
            <li class="{% if each_ballot.id == ballot.id %}active{% endif %}"><a  href="{% url 'voteapp:election_detail_ballot' election.id each_ballot.id %}">{{ each_ballot.ballot_title }}</a></li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

voteapp/templates/voteapp/election_review.html
{% extends 'voteapp/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <h1 class="well well-lg text-center ">{{ election.name }}</h1>
    <h2>Review:</h2>
    <p>Check your candidates/choices and if they are correct press submit below.  Otherwise, return and correct any of your choices.</p>
    <div class="text-center">
    <button class="btn-lg">SUBMIT VOTE</button>
    </div>
</div>
{% endblock %}

voteapp/templates/voteapp/election_summary.html
{% extends 'voteapp/base.html' %}

{% block content %}
<div class="container">
    {% for election_id, e_data in tally.items %}
    <h1 class="well well-lg text-center ">{{ e_data.election.name }}</h1>
        {% for ballot_id, ballot_dict in e_data.ballots.items %}
        <h3 class=" ">{{ ballot_dict.ballot.ballot_title }}</h3>
            <table  class="table table-bordered">
                <tr>
                    <th class="">Count</th><th>Option</th>
                </tr>
                {% if ballot_dict.ranked == 'Win' %}
                    <tr class=" ">
                        <td class="tally_count">{{ ballot_dict.ballot_tally}}</td>
                        <td>{{ballot_dict.name | linebreaksbr}}</td>
                    </tr>
                {% else %}
                    {% for option_id, option_data in ballot_dict.ballot_tally.items %}
                    <tr class=" ">
                        <td class="tally_count">{{ option_data.count}}</td>
                        <td>{{option_data.name | linebreaksbr}}</td>
                    </tr>
                    {% endfor %}
                {% endif %}
            </table>
        {% endfor %}
    {% endfor %}
</div>
{% endblock %}

voteapp/templates/voteapp/elections.html
{% extends 'voteapp/base.html' %}
{% block content %}

    <div class="text-center">
        <h1>Online Voting App</h1>
    </div>
    <div>
    {% if user.is_authenticated %}


        {% if election_list %}
            <h3>Choose an election:</h3>
            <div class="list-group">
            {% for election in election_list %}
                <a class="list-group-item" href="{% url 'voteapp:election_detail' election.id %}">{{ election.name }}</a>
            {% endfor %}
            </div>
        {% else %}
            <p>There are no elections currently available.</p>
        {% endif %}


    {% endif %}
    </div>
{% endblock %}

voteapp/templates/voteapp/index.html
{% extends 'voteapp/base.html' %}
{% block content %}

    <div class="text-center">
        <h1>Welcome to VoteApp!</h1>
    </div>
    <div>
    {% if not user.is_authenticated %}

        <div class="container ">

                <p class="text-center">Please Register or Log In</p>
            <div class="well well-sm ">
                <a class="" href="{% url 'voteapp:register' %}"><button class="btn-lg text-center center_btn">Register</button></a>
            </div>
            <div class=" well well-sm">
                <div>
                    <a class="" href="{% url 'voteapp:login' %}"><button class="btn-lg text-center center_btn" type="submit" >Log in</button></a>
                </div>

            </div>
        </div>
    {% else %}

        <div class="container ">

                <p class="text-center">Where would you like to go?</p>
            <div class="well well-sm ">
                <a class="" href="{% url 'voteapp:elections' %}"><button class="btn-lg text-center center_btn">Elections</button></a>
            </div>
            <div class=" well well-sm">
                <div>
                    <a class="" href="{% url 'voteapp:election_summary' %}"><button class="btn-lg text-center center_btn" type="submit" >Results</button></a>
                </div>

            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

voteapp/templates/voteapp/login.html
{% extends 'voteapp/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="well well-lg text-center">Login</h1>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn-lg text-center" type="submit" >Log in</button>
        </form>
    </div>
{% endblock %}

voteapp/templates/voteapp/logout.html
{% extends 'voteapp/base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
    <h2 class="text-center">Logout</h2>
    <p  class="text-center">You have successfully logged out.</p>
{% endblock %}

voteapp/templates/voteapp/register.html
{% extends 'voteapp/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="well well-lg text-center">Register</h1>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn-lg text-center center_btn" type="submit" >Submit</button>
        </form>
    </div>
{% endblock %}

voteapp/templates/voteapp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'voteapp:detail' question.id %}">Vote again?</a>
</body>
</html>

voteapp/templates/voteapp/view_logs.html
{% extends 'voteapp/base.html' %}
{% block content %}
    <h1>Logs</h1>
    <div class="container-fluid log_table">
        <div class="row">
            <div class="h4 col-sm-3"><u>Time</u></div>
            <div class="h4 col-sm-2"><u>Username</u></div>
            <div class="h4 col-sm-7"><u>Action</u></div>
        </div>
        {% for log in logs %}
        <div class="row">
            <div class="col-sm-3">{{ log.time_stamp }}</div>
            <div class="col-sm-2">{{ log.voter }}</div>
            <div class="col-sm-7">{{ log.action }}</div>
        </div>

        {% endfor %}
    </div>
{% endblock %}